[package]
name = "zen-go-tui"
version = "0.1.0"
edition = "2021"

[lib]
name = "zen_go_tui"
path = "src/lib.rs"

[[bin]]
name = "zen-go-tui"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
ratatui = "0.30"
serde = { version = "1.0", features = ["derive"] }
termprofile = "0.2.2"
terminput = "0.5.14"
terminput-crossterm = { version = "0.4.10", default-features = false, features = ["crossterm_0_29"] }
thiserror = "2.0"
toml = "0.8"
tui-slider = "0.3.2"

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "2.6", default-features = false, features = ["linux-static-hidraw"] }

[target.'cfg(windows)'.dependencies]
hidapi = { version = "2.6", default-features = false, features = ["windows-native"] }
